services:
  bot:
    build: .
    container_name: zipper_bot
    restart: always
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./zipper:/app/zipper
    networks:
      - web

networks:
  web:
    external: true
